# Generated by Django 5.2.2 on 2025-06-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('puesto', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('clave_acceso', models.CharField(max_length=25)),
            ],
        ),
    ]
