# Generated by Django 5.2.3 on 2025-06-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_tokenmedico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenMedico',
        ),
    ]
