# Generated by Django 5.2.2 on 2025-06-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('motivo_consulta', models.TextField()),
                ('amnesis_psiquiatrica', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('plan_terapeutico', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('eventos', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
