# Generated by Django 5.2.3 on 2025-06-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
